FROM arm32v6/alpine:latest
LABEL maintainer="Michael Hansen <hansen.mike@gmail.com>"

COPY etc/qemu-arm-static /usr/bin/

RUN apk update && \
    apk add openjdk8-jre

COPY build/install/jsgf-gen/bin/* /usr/bin/
COPY build/install/jsgf-gen/lib/* /usr/lib/

ENTRYPOINT ["/usr/bin/jsgf-gen"]
